#server:
#  port: 8761
spring:
  application:
    name: discovery-service
eureka:
  server:
    # 关掉自保护
    enableSelfPreservation: false
    # 主动失效检测，5秒
    evictionIntervalTimerInMs: 5000
    # 禁用readOnlyCacheMap
    useReadOnlyResponseCache: false
  client:
    # 定时刷新本地缓存时间：5秒
    registryFetchIntervalSeconds: 5
    #开启安全检查
    healthcheck:
      enabled: true
    # Eureka server的地址,多个用逗号隔开
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    #自己是否注册eureka，因为是eureka server，所以就不注册了
    register-with-eureka: false
    #是否需要同步其他eureka server节点的数据
    fetch-registry: true
  instance:
    # 心跳间隔：5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间：10秒
    lease-expiration-duration-in-seconds: 10
    # 表示是够将自己的ip注册到Eureka Server，默认是false，则表示默认使用微服务所在的操作系统的hostname
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
