server:
  port: 60000
spring:
  profiles:
    active: jdbc
  application:
    name: config-service
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource            # 当前数据源操作类型
    driver-class-name: org.postgresql.Driver              # postgresql驱动包
    url: jdbc:postgresql://192.168.10.103:5432/network_disk_config              # 数据库名称
    username: postgres
    password: haojunjie
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 10
  cloud:
    config:
      server:
        jdbc:
          sql: select key,value from config_info where application=? and profile=? and label=?
    stream:
      kafka:
        binder:
          brokers: 192.168.10.103:9092
    #消息总线配置
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true  #开启总线消息更新功能
eureka:
  client:
    # 定时刷新本地缓存时间：5秒
    registryFetchIntervalSeconds: 5
    #开启安全检查
    healthcheck:
      enabled: true
    # Eureka server的地址,多个用逗号隔开
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # 心跳间隔：5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间：10秒
    lease-expiration-duration-in-seconds: 10
    # 表示是够将自己的ip注册到Eureka Server，默认是false，则表示默认使用微服务所在的操作系统的hostname
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always