server:
  port: 6400
spring:
  application:
    name: message-service
  kafka:
    bootstrap-servers: 127.0.0.1:9092,10.91.159.39:9092
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      transaction-id-prefix: message-application
eureka:
  client:
    # 定时刷新本地缓存时间：5秒
    registryFetchIntervalSeconds: 5
    # Eureka server的地址,多个用逗号隔开
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # 心跳间隔：5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间：10秒
    lease-expiration-duration-in-seconds: 10
    # 表示是够将自己的ip注册到Eureka Server，默认是false，则表示默认使用微服务所在的操作系统的hostname
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*'